In [2]:
import pandas as pd
from konlpy.tag import Kkma
from konlpy.utils import pprint

kkma = Kkma()
pprint(kkma.sentences(u'네,안녕하세요. 반갑습니다.'))

['네, 안녕하세요.', '반갑습니다.']


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
docs = ['this this this book',
       'this can good',
       'cat good shit']

count_model = CountVectorizer(ngram_range=(1,1))
X = count_model.fit_transform(docs)

Xc = (X.T * X)
Xc.setdiag(0)

print(Xc.todense())

[[0 0 0 0 0 3]
 [0 0 0 1 0 1]
 [0 0 0 1 1 0]
 [0 1 1 0 1 1]
 [0 0 1 1 0 0]
 [3 1 0 1 0 0]]


In [4]:
import numpy as np
samples = ['awesome unicorns are awesome','batman forever and ever','I love batman forever']
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2), vocabulary = {'awesome unicorns':0, 'batman forever':1}) 
co_occurrences = bigram_vectorizer.fit_transform(samples)
print('Printing sparse matrix:', co_occurrences)
print('Printing dense matrix (cols are vocabulary keys 0-> "awesome unicorns", 1-> "batman forever")', co_occurrences.todense())
sum_occ = np.sum(co_occurrences.todense(),axis=0)
print('Sum of word-word occurrences:', sum_occ)
print('Pretty printig of co_occurrences count:', zip(bigram_vectorizer.get_feature_names(),np.array(sum_occ)[0].tolist()))

Printing sparse matrix:   (0, 0)	1
  (1, 1)	1
  (2, 1)	1
Printing dense matrix (cols are vocabulary keys 0-> "awesome unicorns", 1-> "batman forever") [[1 0]
 [0 1]
 [0 1]]
Sum of word-word occurrences: [[1 2]]
Pretty printig of co_occurrences count: <zip object at 0x7f97ac351c48>


In [10]:
vectorizer = CountVectorizer(min_df=1)
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]

x = vectorizer.fit_transform(corpus)
x

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [15]:
analyze = vectorizer.build_analyzer()
analyze("This is a text document to analyze.") == (['this','is','text','document','to','analyze'])

True

In [17]:
vectorizer.get_feature_names() == (
['and', 'document', 'first', 'is', 'one','second', 'the', 'third', 'this'])

True

In [18]:
X.toarray()

array([[1, 0, 0, 0, 0, 3],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 0]], dtype=int64)